spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.178.197.206:3306/xiafish
    username: root
    password: 12345

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB

  mail:
    host: smtp.qq.com
    username: 2640115971@qq.com
    password: ruauhiuyxvusdhjf
    default-encoding: utf-8
  redis:
    host: 118.178.197.206
    port: 6379
    database: 0
    password: 12345

mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
server:
  port: 8080
